[package]
name = "c0ls"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
analysis = { path = "../analysis" }
env_logger = "0.9"
log = "0.4"
lsp-server = "0.6"
lsp-types = "0.93"
serde = "1"
serde_json = "1"
walkdir = "2"
