[package]
name = "c0ls"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
analysis = { path = "../analysis" }
lsp-server = "0.5"
lsp-types = "0.86"
rustc-hash = "1"
serde = "1"
serde_json = "1"
walkdir = "2"
