[package]
name = "cli"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"

[dependencies]
codespan-reporting = "0.11"
gumdrop = "0.8"
lex = { path = "../lex" }
parse = { path = "../parse" }
statics = { path = "../statics" }
syntax = { path = "../syntax" }
