[package]
name = "cli"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
analysis = { path = "../analysis" }
gumdrop = "0.8"
rustc-hash = "1"
