[package]
name = "statics"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
hir = { path = "../hir" }
rustc-hash = "1"
uri-db = { path = "../uri-db" }
