[package]
name = "statics"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
rustc-hash = "1"
syntax = { path = "../syntax" }
unwrap-or = { path = "../unwrap-or" }

[features]
unreachable = []
