[package]
name = "uses"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
doctest = false
test = false

[dependencies]
std-lib = { path = "../std-lib" }
syntax = { path = "../syntax" }
uri-db = { git = "https://github.com/azdavis/language-server-util.git" }
