[package]
name = "syntax-gen"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[lib]
doctest = false
test = false

[dependencies]
identifier-case = { path = "../identifier-case" }
proc-macro2 = "1"
quote = "1"
rustc-hash = "1"
ungrammar = "1"
