[package]
name = "syntax-neue"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[dependencies]
event-parse = { path = "../event-parse" }
rowan = "0.10"

[build-dependencies]
syntax-gen = { path = "../syntax-gen" }
