[package]
name = "std-lib"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[lib]
doctest = false

[dependencies]
lex = { path = "../lex" }
lower = { path = "../lower" }
parse = { path = "../parse" }
statics = { path = "../statics" }
