[package]
name = "std-lib"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
lex = { path = "../lex" }
lower = { path = "../lower" }
parse = { path = "../parse" }
statics = { path = "../statics" }
