[package]
name = "fmt"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
doctest = false

[dependencies]
syntax = { path = "../syntax" }

[dev-dependencies]
lex = { path = "../lex" }
parse = { path = "../parse" }
