[package]
name = "uri-db"
version = "0.1.0"
authors = ["Ariel Davis <ariel.z.davis@icloud.com>"]
edition = "2018"
publish = false

[lib]
doctest = false
test = false

[dependencies]
rustc-hash = "1"
url = "2"
